name: Scheduled NAV Refresh

on:
  schedule:
    # Runs at 3:00 AM UTC/8.30 AM IST Monday-Friday
    - cron: '0 3 * * 1-5'
    # Runs at 6:00 PM UTC/11.30PM IST Monday, Wednesday (for NPS)
    - cron: '0 18 * * 1,3'
  workflow_dispatch:        # allows manual triggering


jobs:
  refresh-nav:
    runs-on: ubuntu-latest
    steps:
      - name: Call Mutual Fund NAV Refresh
        run: |
          curl -L -X POST "https://sipgoals.in/api/refresh-nav" -H "x-api-key: ${{ secrets.NAV_REFRESH_API_KEY }}"
      - name: Call NPS NAV Refresh (Monday and Wednesday only)
        if: github.event.schedule == '0 19 * * 1,3'
        run: |
          curl -L -X POST "https://sipgoals.in/api/refresh-nps-nav" -H "x-api-key: ${{ secrets.NAV_REFRESH_API_KEY }}"