name: Scheduled NAV Refresh

on:
  schedule:
    # Runs at 5:00 AM UTC Monday-Friday
    - cron: '0 5 * * 1-5'
    # Runs at 7:00 PM UTC Monday (for NPS)
    - cron: '0 19 * * 1'
  workflow_dispatch:        # allows manual triggering


jobs:
  refresh-nav:
    runs-on: ubuntu-latest
    steps:
      - name: Call Mutual Fund NAV Refresh
        run: |
          curl -X POST "https://sipgoals.in/api/refresh-nav" -H "x-api-key: ${{ secrets.NAV_REFRESH_API_KEY }}"
      - name: Call NPS NAV Refresh (Monday only)
        run: |
          curl -X POST "https://sipgoals.in/api/refresh-nps-nav" -H "x-api-key: ${{ secrets.NAV_REFRESH_API_KEY }}"